name: valor-pro-build-action
description: docker build and push action.
author: valor-pro 
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  username:
    description: 'Username used to log against the Docker registry'
    required: true
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: true
  host:
    description: 'Docker registry host'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash 
    - run: script.sh
      shell: bash
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        HOST: ${{ inputs.host }}
        VALOR_PRO_VERSION: ${{ inputs.VALOR_PRO_VERSION }}
        REPO_NAME: ${{ github.event.repository.name }}